---
apiVersion: k3d.io/v1alpha3 
kind: Simple 
name: mgmt-lcl
servers: 1
agents: 1
image: rancher/k3s:v1.23.3-k3s1 
network: kind
volumes: 
  - volume: /var/run/docker.sock:/var/run/docker.sock
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: 9001:9001 # wgc ui
    nodeFilters:
      - server:0
      - agent:*
  - port: 4040:4040 # scope
    nodeFilters:
      - server:0
      - agent:*
options:
  k3s: # options passed on to K3s itself
    extraArgs: # additional arguments passed to the `k3s server|agent` command; same as `--k3s-arg`
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
  